### ISSUE TITLE
Exception when trying UNREAL

### ISSUE THREAD

**Issue by zhuchiheng** [lancelee82/rockrose#1]
Hi,
My enviroment: ubuntu16.04, python3.5, keras 1.2, tensoflow 0.12
Contents of exception:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benna/workspace/rockrose-master/unr_sandroad_1.py", line 112, in <module>
    main()
  File "/home/benna/workspace/rockrose-master/unr_sandroad_1.py", line 85, in main
    model = rr_model_unr.RRModelUnreal(md_cfg)
  File "/home/benna/workspace/rockrose-master/rockrose/models/unreal.py", line 92, in __init__
    self.model_init()
  File "/home/benna/workspace/rockrose-master/rockrose/models/unreal.py", line 174, in model_init
    activation='relu', name='deconv1'))
  File "/home/benna/anaconda3/lib/python3.5/site-packages/keras/models.py", line 327, in add
    output_tensor = layer(self.outputs[0])
  File "/home/benna/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py", line 569, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/benna/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py", line 632, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/benna/anaconda3/lib/python3.5/site-packages/keras/engine/topology.py", line 164, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/benna/anaconda3/lib/python3.5/site-packages/keras/layers/convolutional.py", line 636, in call
    filter_shape=self.W_shape)
  File "/home/benna/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2243, in deconv2d
    padding=padding)
  File "/home/benna/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1078, in conv2d_transpose
    name=name)
  File "/home/benna/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 489, in conv2d_backprop_input
    data_format=data_format, name=name)
  File "/home/benna/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 508, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'input_sizes' of 'Conv2DBackpropInput' Op has type float32 that does not match expected type of int32.
```

Any idea about this issue ?
Thx!

**Comment by zhuchiheng** [comment]
OK, I figured it out:
self.pc_wh and self.pc_cw of RRModelUnreal should be integers...
